import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/layout/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const setThemeMode = `
    (function() {
      const theme = localStorage.getItem('theme-storage');
      const parsedTheme = theme ? JSON.parse(theme).state.theme : 'light';
      document.documentElement.classList.remove('light', 'dark');
      document.documentElement.classList.add(parsedTheme);
    })();
  `;

  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: setThemeMode,
          }}
        />
      </head>
      <body className={inter.className}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
